apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: web
- apiVersion: v1
  kind: Namespace
  metadata:
    name: words
- apiVersion: v1
  kind: Namespace
  metadata:
    name: db
