apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: web
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
  - name: web-service-port
    protocol: TCP
    port: 80
    targetPort: web-port
