apiVersion: v1
kind: Service
metadata:
  name: words
  namespace: words
spec:
  selector:
    app: words
  ports:
  - name: words-service-port
    protocol: TCP
    port: 8080
    targetPort: words-port
